# Generated by Django 4.2.11 on 2024-03-22 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 22, 2, 25, 17, 585734, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
