# Generated by Django 4.2.11 on 2024-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_collation='case_insensitive', max_length=50, null=True, unique=True),
        ),
    ]
